// Get all poems
GET {{URL}}/poems

###
// Get 1 poem by ID
GET {{URL}}/poems/1

###
// Post poem
POST {{URL}}/poems

###
//Update poem
PUT {{URL}}/poems/2
###

//Delete poem
DELETE {{URL}}/poems/3

###
//Populate the database with poems
POST {{URL}}/poems/populateDatabase