package dat.enums;

public enum PoemTypes {
    HAIKU, LIMERICK, SENRYU, TANKA, SONNET, VILLANELLE, ACROSTIC, ELEGY, ODE, GHAZAL,
    SESTINA, PANTOUM, TERZA_RIMA, TRIOLET, RONDEL, RONDEAU, BALLAD, EPIC, FREE_VERSE,
    LYRIC, NARRATIVE, PROSE, RHYMED_VERSE, BLANK_VERSE, CONCRETE, FOUND, LIGHT, VISUAL
    }